language: python
python:
  - "3.6.5"
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database testdb; create database testingdb' -U postgres
script:
  - pytest test --cov=app --cov-report term-missing
after_success:
  - coveralls
